name = "FLOWExaFMM"
uuid = "a07d1f4e-0e34-4d8b-bfef-e5b961477d34"
authors = ["Eduardo J. Alvarez <Edo.AlvarezR@gmail.com>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"

[compat]
julia = "1.4"
CxxWrap = "0.11.0"
